apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  ports:
    - port: 80
  selector:
    app: nextcloud
    tier: frontend
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-main-pvc
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-pvc
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  selector:
    matchLabels:
      app: nextcloud
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nextcloud
        tier: frontend
    spec:
      containers:
        - image: nextcloud:apache
          name: nextcloud
          env:
            - name: MYSQL_HOST
              value: nextcloud-mysql
            - name: MYSQL_DATABASE
              value: nextcloud_db
            - name: MYSQL_USER
              value: nextcloud_user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-nc-user-pass
                  key: password
            - name: MYSQl_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-pass
                  key: password
            - name: NEXTCLOUD_ADMIN_USER
              value: tom
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-admin-pass
                  key: password
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: docs.purlfamily.local docs.tompurl.com docs.destrocodpiece.wtf
            - name: APACHE_DISABLE_REWRITE_IP
              value: "1"
            - name: TRUSTED_PROXIES
              value: 167.172.11.230
          ports:
            - containerPort: 80
              name: nextcloud
          volumeMounts:
            - name: nextcloud-persistent-main-storage
              mountPath: /var/www/html
            - name: nextcloud-persistent-data-storage
              mountPath: /var/www/html/data
      initContainers:
        - name: nextcloud-data-chmod-fix
          image: busybox
          command: ["/bin/chmod","-R","0770", "/data"]
          volumeMounts:
            - name: nextcloud-persistent-data-storage
              mountPath: /data
        - name: nextcloud-data-chown-fix
          image: busybox
          command: ["/bin/chown","-R","33:33", "/data"]
          volumeMounts:
            - name: nextcloud-persistent-data-storage
              mountPath: /data
      securityContext:
        fsGroup: 33
      volumes:
        - name: nextcloud-persistent-main-storage
          persistentVolumeClaim:
            claimName: nextcloud-main-pvc
        - name: nextcloud-persistent-data-storage
          persistentVolumeClaim:
            claimName: nextcloud-data-pvc

